backend:
  name: github
  repo: responsibleIT/Responsible-it
  branch: main
  base_url: http://213.108.108.83/
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
i18n:
  structure: multiple_folders
  locales: [ nl, en ]
  default_locale: nl
collections:
  - name: "community" # Used in routes, e.g., /admin/collections/blog
    label: "Community" # Used in the UI
    folder: "content/dutch/community" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'markdown'
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Date", name: "date", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Summary", name: "summary", widget: "text" },
      - {label: "Body", name: "body", widget: "markdown"}

